### ISSUE TITLE
Rules to keep in mind

### ISSUE THREAD

**Issue by ghost** [admin341/INSTA341#18]
1. Always reference your commit message with issue number
2. Every pull request has to have a reviewer and an assignee
3. Issues has to have an assignee

**Comment by vithura14** [comment]
I will take that under consideration for my next operations.
Thank you for the information!

**Comment by nouj** [comment]
Will be noted for all future commits, pull requests and issues.

**Comment by nuzurie** [comment]
Cool. Cool cool cool.
