### ISSUE TITLE
Change the follow feature to allow following from the user profile page.

### ISSUE THREAD

**Issue by nuzurie** [admin341/INSTA341#46]
Currently follow feature is only implemented on home page where it's making use of post ids. One should be able to follow a user even if they haven't posted anything.

**Comment by nuzurie** [comment]
The follow feature needs to be reintegrated with profile_view page. The user can no longer follow self -- another requirement -- anywhere except from their own profile_view page. Please fix.

**Comment by nuzurie** [comment]
Please also implement the like feature in the same commit. Thanks.

**Comment by nouj** [comment]
This has been solved. Thanks!
