### ISSUE TITLE
As a user, I want to comment on my post pictures so that it can be descriptive to other users.

### ISSUE THREAD

**Issue by amneet270** [admin341/INSTA341#7]
**Task Breakdown**
- Comment block is the same size as the picture's width. (1)
- Adding the use of emojis in comment section. (7)
- Comments are displayed in order of most recent comment. (4)
- Username displayed once comment has been added. (2)

**Comment by instamine** [comment]
Reviewed:
-Changed milestone from 1 to 2
-Deleted wrong description and restated the proper utility.
