### ISSUE TITLE
As a user, I want to follow my friends and celebrities so that I can view their pictures and comments.

### ISSUE THREAD

**Issue by amneet270** [admin341/INSTA341#8]
**Task breakdown**
- Whoever you follow, you can unfollow. (7)
- You can follow anyone as long as you are logged in as a user. (2)

**Comment by instamine** [comment]
Reviewed: 
-Changed milestone from 1 to 2

**Comment by instamine** [comment]
Reviewed: 
-Deleted wrong description and restated the proper utility.
